/* eslint-disable import/prefer-default-export */
// export { default as KompasWwwSubmodulesSample } from './kompas-www-submodules-sample.vue';
export { default as KsmSingleTitle } from './single/Title.vue'
export { default as KsmSingleExcerpt } from './single/Excerpt.vue'
export { default as KsmSingleCredits } from './single/Credits.vue'
export { default as KsmSingleParagraph } from './single/Paragraph.vue'
export { default as KsmSingleBlockquote } from './single/Blockquote.vue'
export { default as KsmSingleCaption } from './single/Caption.vue'
export { default as KsmSingleH1 } from './single/H1.vue'
export { default as KsmSingleH2 } from './single/H2.vue'
export { default as KsmSingleH3 } from './single/H3.vue'
export { default as KsmSingleH4 } from './single/H4.vue'
export { default as KsmSingleH5 } from './single/H5.vue'
export { default as KsmSingleH6 } from './single/H6.vue'
export { default as KsmSingleOl } from './single/Ol.vue'
export { default as KsmSingleImage } from './single/Image.vue'
export { default as KsmSingleText } from './single/Text.vue'
export { default as KsmSingleUl } from './single/Ul.vue'
export { default as KsmSingleRaw } from './single/Raw.vue'
